#+title: İsmail Efe Top's Doom Emacs Config
#+AUTHOR: İsmail Efe Top
#+PROPERTY: header-args :tangle /Users/ismailefetop/.config/doom/config.el
#+auto_tangle: t
# first year in uni, mba2022
# second year in uni, mba2022

* One Liners
** Lexical Binding
#+begin_src elisp
;;; ~/.config/doom/config.el -*- lexical-binding: t; -*-
#+end_src

** My contact information
#+begin_src elisp
(setopt user-full-name "İsmail Efe Top"
      user-mail-address "ismailefetop@gmail.com")
#+end_src

** Setting the default shell
#+begin_src elisp
(setopt shell-file-name (executable-find "bash"))
(setq-default vterm-shell (executable-find "fish"))
(setq-default explicit-shell-file-name (executable-find "fish"))
#+end_src

** Theme
#+begin_src elisp
(setopt doom-theme 'kanagawa)
#+end_src

** Font
#+begin_src elisp
(setopt doom-font (font-spec :family "JetBrains Mono" :size 22))
#+end_src

** Dashboard Customization
In doom dashboard, leave only the splash image
#+begin_src elisp
(setopt +doom-dashboard-functions '(doom-dashboard-widget-banner))
#+end_src

** Disable Confirm on exit
#+begin_src elisp
(setopt confirm-kill-emacs nil)
#+end_src

** Disable Delays
#+begin_src elisp
(setopt bookmark-search-delay 0.0)
(setopt mouse-scroll-delay 0.0)
#+end_src

** Disable autosave
#+begin_src elisp
(setopt auto-save-default nil)
#+end_src

** Disable Backup
#+begin_src elisp
(setopt backup-inhibited t)
#+end_src

** Automatically Kill Running Processes on Exit
[[https://emacsredux.com/blog/2020/07/18/automatically-kill-running-processes-on-exit/][Emacs Redux Article]]

#+begin_src elisp
(setopt confirm-kill-processes nil)
#+end_src

** Enable Word Count in the Doom Modeline
#+begin_src elisp
(setopt doom-modeline-enable-word-count t)
#+end_src

** Disable Line Numbers
#+begin_src elisp
(setopt display-line-numbers-type nil)
#+end_src

** Disable unnecessary new os windows
#+begin_src elisp
(setopt use-dialog-box nil)
#+end_src

** Deleted files to trash
#+begin_src elisp
(setopt delete-by-moving-to-trash t)
#+end_src

** Make calendar start on Monday
#+begin_src elisp
(setopt calendar-week-start-day 1)
#+end_src

** Automatically updating feed when opening elfeed
#+begin_src elisp :tangle no
(add-hook! 'elfeed-search-mode-hook #'elfeed-update)
#+end_src

** Bib Locations :dir:
#+begin_src elisp
(setopt org-cite-global-bibliography '("/Users/ismailefetop/uni/citation/bib.bib"))
(setopt bibtex-completion-bibliography '("/Users/ismailefetop/uni/citation/bib.bib"))
(setopt citar-bibliography '("/Users/ismailefetop/uni/citation/bib.bib"))
(setopt org-cite-csl-styles-dir "/Users/ismailefetop/uni/citation/styles/")
#+end_src

** Make images adjust to width
#+begin_src elisp
(setopt org-image-actual-width nil)
#+end_src

** Super-save
#+begin_src elisp
;;(super-save-mode +1)
#+end_src

** Opening Large Files
#+begin_src elisp
;; warn when opening files bigger than 200MB
(setopt large-file-warning-threshold 200000000)
#+end_src

** Disable hl-line-mode
#+begin_src elisp
(remove-hook 'doom-first-buffer-hook #'global-hl-line-mode)
#+end_src

** Make the title bar text empty :mac:
#+begin_src elisp
(when (memq system-type '(darwin))
  (setopt ns-use-proxy-icon nil)
  (setopt frame-title-format nil)
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark)))
#+end_src

** Sets olivettis body width
#+begin_src elisp
(setopt olivetti-body-width 94)
#+end_src

** Open olivetti Mode on Text Mode buffers
#+begin_src elisp
(add-hook 'text-mode-hook 'olivetti-mode)
#+end_src

** Enable rendering SF symbols on macOS
[[https://developer.apple.com/fonts/][SF Pro font]] is needed for this to work.
#+begin_src elisp
(when (memq system-type '(darwin))
  (set-fontset-font t nil "SF Pro Display" nil 'append))
#+end_src

** Set undo limit to 80mb
#+begin_src elisp
(setopt undo-limit 80000000)
#+end_src

** Fine tuning the evil-undo
#+begin_src elisp
(setopt evil-want-fine-undo t)
#+end_src

** Activate org-pandoc-import
#+begin_src elisp
(use-package! org-pandoc-import :after org)
#+end_src

** Enable valign
#+begin_src elisp
(add-hook 'org-mode-hook #'valign-mode)
#+end_src

* Keybindings
** Global
#+begin_src elisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+end_src

** Evil
#+begin_src elisp
(define-key evil-normal-state-map "ç" 'ispell)
(define-key evil-normal-state-map "ö" 'ispell-word)
(define-key evil-normal-state-map "ş" 'efe/google-search)
(define-key evil-normal-state-map "Ş" 'efe/first-result-url)
(define-key evil-normal-state-map "ğ" 'efe/tureng-english)
(define-key evil-normal-state-map "ü" 'efe/tureng-turkish)
(define-key evil-normal-state-map "Ğ" 'efe/tureng-en-fr)
(define-key evil-normal-state-map "Ü" 'efe/tureng-fr-en)
#+end_src

** Stop font resizing when pressing control while scrolling
#+begin_src elisp
(global-set-key (kbd "<pinch>") 'ignore)
(global-set-key (kbd "<C-wheel-up>") 'ignore)
(global-set-key (kbd "<C-wheel-down>") 'ignore)
#+end_src

* Pandoc
** Set Pandoc Binary :dir:
#+begin_src elisp
(setopt pandoc-binary "/opt/homebrew/bin/pandoc")
#+end_src

** Global Settings/Data File :dir:
#+begin_src elisp
(setopt pandoc-data-dir "/Users/ismailefetop/.config/doom/etc/pandoc/")
#+end_src

* Org
** Org directories
*** Main Directory :dir:
#+begin_src elisp
(setopt org-directory "/Users/ismailefetop/.orgs/org/")
#+end_src

*** Other Org Directories :dir:
#+begin_src elisp
(setopt org-agenda-files '("/Users/ismailefetop/uni/current-course/" "/Users/ismailefetop/.orgs/org/" "/Users/ismailefetop/ideas/"))
#+end_src

** Trusting the org-blocks in org automatically
#+begin_src elisp
(setopt org-confirm-babel-evaluate nil)
#+end_src

** Change the look of org-agenda to-do view.
#+begin_src elisp
(setopt org-agenda-prefix-format
      '((agenda . " %i %-12:c%?-12t% s")
        (todo   . " ")
        (tags   . " %i %-12:c")
        (search . " %i %-12:c")))
#+end_src

** Org Auto Tangle
#+begin_src elisp
(add-hook 'org-mode-hook 'org-auto-tangle-mode)
#+end_src

* Functions
** Google Search
#+begin_src elisp
(defun efe/google-search (arg)
  "Search the current word or region on Google using browse-url.
With prefix argument ARG, prompt for a search term instead.
If region is active, use the region text as the search term."
  (interactive "P")
  (let* ((bounds (if (use-region-p)
                     (cons (region-beginning) (region-end))
                   (bounds-of-thing-at-point 'word)))
         (text (cond
                (arg (read-string "Google search: "))
                (bounds (buffer-substring-no-properties (car bounds) (cdr bounds)))
                (t nil)))
         (encoded-text (when text (url-hexify-string text))))
    (if encoded-text
        (browse-url (concat "https://www.google.com/search?q=" encoded-text))
      (user-error "No text to search for"))))
#+end_src

** Get the first result
[[https://gist.github.com/Ektaynot/46681539aa1c030b3a58986e7f3df397][Link to the firstresult script.]]
#+begin_src elisp
(defun efe/first-result-url ()
  ;; Written by ChatGPT
  "Get the first url from a google search."
  (interactive)
  (let ((word (thing-at-point 'word)))
    (if word
        (let ((output (shell-command-to-string (format "firstresult -w %s" word))))
          (message output))
      (message "No word found at point."))))

#+end_src

** Copy Path Function
#+begin_src elisp
(defun efe/select-and-copy-file-path ()
  ;; Written by chatgpt
  "Copy the selected file's path."
  (interactive)
  (let ((file-path (read-file-name "Select a file: ")))
    (kill-new file-path)
    (message "Copied file path: %s" file-path)))
#+end_src

** Blog Html Insert
#+begin_src elisp
(defun efe/insert-html-blog-template ()
  ;; Written by ChatGPT
  "Inserts HTML_HEAD lines at the first empty line and html code at the end of the buffer."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((empty-line (progn (re-search-forward "^$" nil t) (point))))
      (goto-char empty-line)
      (insert "\n#+HTML_HEAD: <link rel=\"stylesheet\" type=\"text/css\" href=\"/templates/style.css\" />\n")
      (insert "#+HTML_HEAD: <meta name=\"theme-color\" content=\"#fffcf0\">\n")
      (insert "#+HTML_HEAD: <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/favicon/apple-touch-icon.png\">\n")
      (insert "#+HTML_HEAD: <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon/favicon-32x32.png\">\n")
      (insert "#+HTML_HEAD: <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/favicon/favicon-16x16.png\">\n")
      (insert "#+HTML_HEAD: <link rel=\"manifest\" href=\"/favicon/site.webmanifest\">\n")))
  (goto-char (point-max))
  (insert "\n\n")
  (insert "#+BEGIN_EXPORT html\n")
  (insert "<div class=\"bottom-header\">\n")
  (insert "  <a class=\"bottom-header-link\" href=\"/\">Home</a>\n")
  (insert "  <a href=\"mailto:ismailefetop@gmail.com\" class=\"bottom-header-link\">Mail Me</a>\n")
  (insert "  <a class=\"bottom-header-link\" href=\"/feed.xml\" target=\"_blank\">RSS</a>\n")
  (insert "  <a class=\"bottom-header-link\" href=\"https://github.com/Ektaynot/ismailefe_org\" target=\"_blank\">Source</a>\n")
  (insert "</div>\n")
  (insert "<div class=\"firechickenwebring\">\n")
  (insert "  <a href=\"https://firechicken.club/efe/prev\">←</a>\n")
  (insert "  <a href=\"https://firechicken.club\">🔥⁠🐓</a>\n")
  (insert "  <a href=\"https://firechicken.club/efe/next\">→</a>\n")
  (insert "</div>\n")
  (insert "#+END_EXPORT\n"))

#+end_src

** Term2anki
#+begin_src elisp
(defun efe/term2anki (file)
  "Turn org notes into csv files that anki can read, creating a new file."
  (interactive "FExport notes to: ")
  (let* ((regex (rx bol (in "+-") " " (group (1+ nonl)) ": " (group (1+ nonl))))
         (buf (find-file-noselect file))
         (output "")
         (new-file (concat file ".csv")))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward regex nil t)
        (setopt output (concat output (format "%s;%s\n" (match-string 1)
                                            (match-string 2)))))
      (with-temp-file new-file
        (insert output))
      (kill-buffer buf)
      (message "Export done. New file: %s" new-file))))
#+end_src

** Remove Leading Whitespaces
#+begin_src elisp
(defun efe/remove-leading-spaces ()
  ;; Written by ChatGPT
  "Remove leading spaces until the first non-space character of each line."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (while (not (eobp))
      (beginning-of-line)
      (skip-chars-forward " \t")
      (delete-region (point-at-bol) (point))
      (forward-line))))
#+end_src

** Tureng Functions
*** Turkish to english
#+begin_src elisp
(defun efe/tureng-turkish ()
  ;; Written by ChatGPT
  "Translate the word at point using tureng program."
  (interactive)
  (let ((word (thing-at-point 'word)))
    (if word
        (let ((output (shell-command-to-string (format "tureng -l t -t e -w %s" word))))
          (message output))
      (message "No word found at point."))))
#+end_src

*** English to turkish
#+begin_src elisp
(defun efe/tureng-english ()
  ;; Written by ChatGPT
  "Translate the word at point using tureng program."
  (interactive)
  (let ((word (thing-at-point 'word)))
    (if word
        (let ((output (shell-command-to-string (format "tureng -l e -t t -w %s" word))))
          (message output))
      (message "No word found at point."))))
#+end_src

*** English to French
#+begin_src elisp
(defun efe/tureng-en-fr ()
  ;; Written by ChatGPT
  "Translate the word at point using tureng program."
  (interactive)
  (let ((word (thing-at-point 'word)))
    (if word
        (let ((output (shell-command-to-string (format "tureng -l e -t f -w %s" word))))
          (message output))
      (message "No word found at point."))))
#+end_src

*** French to English
#+begin_src elisp
(defun efe/tureng-fr-en ()
  ;; Written by ChatGPT
  "Translate the word at point using tureng program."
  (interactive)
  (let ((word (thing-at-point 'word)))
    (if word
        (let ((output (shell-command-to-string (format "tureng -l f -t e -w %s" word))))
          (message output))
      (message "No word found at point."))))
#+end_src
** Open in VSCode
#+begin_src elisp
(defun efe/open-in-vscode ()
  ;; Written by ChatGPT
  "Open the current file in Visual Studio Code."
  (interactive)
  (let ((file-path (buffer-file-name)))
    (if file-path
        (shell-command (format "code %s" (shell-quote-argument file-path)))
      (message "Buffer is not visiting a file"))))
#+end_src

** Open Project in VSCode
#+begin_src elisp
(defun efe/open-buffer-as-vscode-project ()
  ;; Written by ChatGPT
  "Open the current buffer's file in Visual Studio Code with the project directory as the workspace."
  (interactive)
  (let ((file-path (buffer-file-name))
        (project-root (or (project-root (project-current)) ;; Detect project root dynamically
                          (locate-dominating-file default-directory ".git") ;; Fallback to git root
                          default-directory))) ;; Fallback to the current directory
    (if file-path
        (progn
          (shell-command (format "code --folder-uri %s --goto %s"
                                 (shell-quote-argument (expand-file-name project-root))
                                 (shell-quote-argument (expand-file-name file-path))))
          (message "Opened file %s in VSCode using project root %s" file-path project-root))
      (message "Buffer is not visiting a file"))))

#+end_src

** Dos2unix
#+begin_src elisp
(defun dos2unix ()
  "Replace DOS eolns CR LF with Unix eolns CR"
  (interactive)
    (goto-char (point-min))
      (while (search-forward "\r" nil t) (replace-match "")))
#+end_src

* Snippets
** Default Org Template
This line makes the insides of __orgtemplate.org file append on every newly created org file.
#+begin_src elisp
(set-file-template! "\\.org$" :trigger "__orgtemplate.org" :mode 'org-mode)
#+end_src

* Defaults
** Email Client
#+begin_src elisp
(setq browse-url-mailto-function 'browse-url-generic)
(setopt browse-url-generic-program "open")
#+end_src

** Openwith Defaults
#+begin_src elisp
(add-hook 'emacs-startup-hook 'openwith-mode)
(setopt openwith-associations
      '(("\\.pdf\\'" "open" (file))
        ("\\.docx\\'" "open" (file))
        ("\\.psd\\'" "open" (file))
        ;;("\\.jpeg\\'" "open" (file))
        ;;("\\.jpg\\'" "open" (file))
        ;;("\\.png\\'" "open" (file))
        ("\\.pptx\\'" "open" (file))
        ("\\.ppt\\'" "open" (file))
        ("\\.epub\\'" "open" (file))
        ;; ("\\.svg\\'" "open" (file))
        ("\\.gif\\'" "open" (file))
        ))
#+end_src

* Spellchecking :dir:
** hunspell
Here is the [[https://web.archive.org/web/20240520082706/https://old.reddit.com/r/emacs/comments/dgj0ae/tutorial_spellchecking_with_hunspell_170_for/][tutorial I followed]].
#+begin_src elisp
(setopt ispell-program-name "hunspell")
(setopt ispell-hunspell-dict-paths-alist '(("en_US" "/Users/ismailefetop/.config/dict/en_US.aff")))
(setopt ispell-local-dictionary "en_US")
(setopt ispell-local-dictionary-alist '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "en_US") nil utf-8)))
(flyspell-mode 1)
#+end_src
** Skip certain sections
Thanks to Endless Parentheses for the [[https://endlessparentheses.com/ispell-and-org-mode.html][wonderful post]].
#+begin_src elisp
(defun endless/org-ispell ()
  (make-local-variable 'ispell-skip-region-alist)
  (add-to-list 'ispell-skip-region-alist '(org-property-drawer-re))
  (add-to-list 'ispell-skip-region-alist '("~" "~"))
  (add-to-list 'ispell-skip-region-alist '("=" "="))
  (add-to-list 'ispell-skip-region-alist '("^#\\+begin_src" . "^#\\+end_src"))
  (add-to-list 'ispell-skip-region-alist '("^#\\+HTML_HEAD:" . ">"))
  (add-to-list 'ispell-skip-region-alist '("^#\\+HTML" . ">"))
  (add-to-list 'ispell-skip-region-alist '("^#\\+begin_export" . "^#\\+end_export")))
(add-hook 'org-mode-hook #'endless/org-ispell)
#+end_src

* Startup
** Maximize on startup using Rectangle :mac:
#+begin_src elisp
;; Requires the mac app Rectangle to function.
(defun rectangle-maximize ()
  "Execute a shell command when Emacs starts."
  (call-process-shell-command "open -g 'rectangle://execute-action?name=maximize'" nil 0))

(add-hook 'window-setup-hook 'toggle-frame-maximized t)

(when (memq system-type '(darwin))
  (add-hook 'emacs-startup-hook 'rectangle-maximize)
)
#+end_src

* Misc.
** Make emacs silent
#+begin_src elisp :tangle no
(setopt byte-compile-warnings '(not obsolete))
(setopt warning-suppress-log-types '((comp) (bytecomp)))
(setopt native-comp-async-report-warnings-errors 'silent)
(setopt inhibit-startup-echo-area-message (user-login-name))
(setopt visible-bell t)
(setopt ring-bell-function 'ignore)
(setopt set-message-beep 'silent)
#+end_src

** Auto-create Missing Directories
[[https://emacsredux.com/blog/2022/06/12/auto-create-missing-directories/][Emacs Redux Article]]
#+begin_src elisp
(defun er-auto-create-missing-dirs ()
  (let ((target-dir (file-name-directory buffer-file-name)))
    (unless (file-exists-p target-dir)
      (make-directory target-dir t))))

(add-to-list 'find-file-not-found-functions #'er-auto-create-missing-dirs)
#+end_src

** Remove branch name from doom-modeline when on master
#+begin_src elisp
(defadvice! fixed-doom-modeline-update-vcs-a (&rest _)
  :after #'doom-modeline-update-vcs
  (and doom-modeline--vcs
       (equal (alist-get 'text doom-modeline--vcs) "master")
       (setf (alist-get 'text doom-modeline--vcs) "")))
#+end_src
* Testing
#+begin_src elisp
#+end_src
