* İsmail Efe's Doom Config

This is a [[https://github.com/doomemacs/doomemacs][Doom Emacs]] config and is mostly focused on writing improvements. It uses a literate config. You can check what everything does and why it does that certain thing in [[https://github.com/Ektaynot/doom/blob/master/config.org][config.org]]. Couple of things about my config are

- [[https://github.com/rnkn/olivetti][Olivetti]] Mode enabled on text modes
- Automatic resizing on mac thanks to [[https://rectangleapp.com/][rectangle]]
- Autosave thanks to [[https://github.com/bbatsov/super-save][supersave]]
- Removed line numbers and hl-line-mode
- Spellcheck that uses Hunspell, tutorial [[https://web.archive.org/web/20240520082706/https://old.reddit.com/r/emacs/comments/dgj0ae/tutorial_spellchecking_with_hunspell_170_for/][here]]

** Installation

If you are on MacOS, all you have to do is clone this repo to your .config folder. If you are on Linux or Windows, take a look at the config.org and remove anything that has :mac: tag or you deem is related to mac and then clone it into your .config folder.

** Reach out to me

Feel free to give me feedback or suggestions via [[mailto:ismailefetop@gmail.com][email]]
